#pragma once

#define PLUGIN_NAME "Flex DSP"
#define PLUGIN_UI_DESC "Switch DSP based on track metadata."

#define COMPONENT_VERSION_MAJOR 1
#define COMPONENT_VERSION_MINOR 0
#define COMPONENT_VERSION_PATCH 0
#define COMPONENT_VERSION_SUB_PATCH 0

//#define FIX_VER

#define MAKE_STRING(text) #text
#ifdef FIX_VER
#define MAKE_COMPONENT_VERSION(major,minor,patch) MAKE_STRING(major) "." MAKE_STRING(minor) "." MAKE_STRING(patch)
#define FOO_COMPONENT_VERSION MAKE_COMPONENT_VERSION(COMPONENT_VERSION_MAJOR,COMPONENT_VERSION_MINOR,COMPONENT_VERSION_PATCH)
#else
#define MAKE_COMPONENT_VERSION(major,minor) MAKE_STRING(major) "." MAKE_STRING(minor)
//"1.15"
#define FOO_COMPONENT_VERSION MAKE_COMPONENT_VERSION(COMPONENT_VERSION_MAJOR,COMPONENT_VERSION_MINOR)
#endif

#define MAKE_DLL_VERSION(major,minor,patch,subpatch) MAKE_STRING(major) "." MAKE_STRING(minor) "." MAKE_STRING(patch) "." MAKE_STRING(subpatch)
#define MAKE_API_SDK_VERSION(sdk_ver, target_ver) MAKE_STRING(sdk_ver) " " MAKE_STRING(target_ver)

//0.1.2.3 & "0.1.2.3"
#define DLL_VERSION_NUMERIC COMPONENT_VERSION_MAJOR, COMPONENT_VERSION_MINOR, COMPONENT_VERSION_PATCH, COMPONENT_VERSION_SUB_PATCH
#define DLL_VERSION_STRING MAKE_DLL_VERSION(COMPONENT_VERSION_MAJOR,COMPONENT_VERSION_MINOR,COMPONENT_VERSION_PATCH,COMPONENT_VERSION_SUB_PATCH)
//fb2k ver
#define PLUGIN_FB2K_SDK MAKE_API_SDK_VERSION(FOOBAR2000_SDK_VERSION, FOOBAR2000_TARGET_VERSION)

#define COMPONENT_NAME "foo_flex_dsp"
#define COMPONENT_YEAR "2023"

#define COMPONENT_NAME_DLL COMPONENT_NAME ".dll"
